theme = "transparent"

[editor]
mouse = false
scrolloff = 999
line-number = "relative"  
bufferline = "multiple"

[editor.cursor-shape] 
insert = "bar"
normal = "block"
select = "underline"

[editor.soft-wrap]
enable = true

[keys.insert]
"C-c" = [
  "collapse_selection",
  "keep_primary_selection",
  "normal_mode"
]
 
[keys.normal]
"}" = "goto_next_paragraph"
"{" = "goto_prev_paragraph"
"n" = "move_char_left"
esc = ["collapse_selection", "keep_primary_selection"]
"C-c" = [
  "collapse_selection",
  "keep_primary_selection",
]
"C-x" = "toggle_comments"

[keys.select]
"}" = "goto_next_paragraph"
"{" = "goto_prev_paragraph"
"C-c" = [
  "collapse_selection",
  "keep_primary_selection",
  "normal_mode"
]

"C-x" = "toggle_comments"

[editor.indent-guides]
render = false
character = "|"
skip-levels = 1
